SELECT A.CAR_ID, A.CAR_TYPE,
CAST(A.DAILY_FEE * (100 - C.RATE) / 100 * 30 AS UNSIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN (SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_CAR
      WHERE CAR_ID NOT IN (
          SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE MONTH(START_DATE) <= 11 AND MONTH(END_DATE) >= 11)) B
ON A.CAR_ID = B.CAR_ID
JOIN (SELECT CAR_TYPE, CAST(DISCOUNT_RATE AS SIGNED) AS RATE
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
      WHERE DURATION_TYPE = '30일 이상') C
ON A.CAR_TYPE = C.CAR_TYPE
WHERE 500000 <= A.DAILY_FEE * (100 - C.RATE) / 100 * 30
AND A.DAILY_FEE * (100 - C.RATE) / 100 * 30 < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
