SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * (100 - IFNULL(C.RATE, 0)) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN (SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_CAR
      WHERE CAR_ID NOT IN (
          SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-01')) B ON A.CAR_ID = B.CAR_ID
LEFT JOIN (SELECT CAR_TYPE, CAST(DISCOUNT_RATE AS SIGNED) AS RATE
           FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
           WHERE DURATION_TYPE = '30일 이상') C ON A.CAR_TYPE = C.CAR_TYPE
WHERE 500000 <= A.DAILY_FEE * (100 - IFNULL(C.RATE, 0)) / 100 * 30
AND A.DAILY_FEE * (100 - IFNULL(C.RATE, 0)) / 100 * 30 < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
