SELECT A.PRODUCT_ID, PRODUCT_NAME, AMOUNT * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT AS A
JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
      FROM FOOD_ORDER
      WHERE PRODUCE_DATE LIKE '2022-05-%'
      GROUP BY PRODUCT_ID) B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;

