SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,
COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021-%'), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE AS A
JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE JOINED LIKE '2021-%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
