SELECT M.HISTORY_ID, CAST(S.DAILY_FEE * (100 - IFNULL(S.DISCOUNT_RATE, 0)) / 100 * S.DATE AS SIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS M
JOIN (
    SELECT A.HISTORY_ID, DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 AS DATE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
    JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON B.CAR_TYPE = C.CAR_TYPE 
    AND REPLACE(DURATION_TYPE, '일 이상', '') <= DATEDIFF(END_DATE, START_DATE) + 1
    WHERE B.CAR_TYPE = '트럭'
    GROUP BY A.HISTORY_ID
    ORDER BY REPLACE(DURATION_TYPE, '일 이상', '') DESC) S 
ON M.HISTORY_ID = S.HISTORY_ID
ORDER BY FEE DESC, M.HISTORY_ID DESC;
