SELECT APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT AS A
JOIN DOCTOR B ON DR_ID = MDDR_ID
JOIN PATIENT C ON A.PT_NO = C.PT_NO
WHERE A.MCDP_CD = 'CS' 
AND APNT_CNCL_YN = 'N' 
AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY APNT_YMD;
