SELECT A.FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO AS A
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE) B 
ON A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.FAV 
ORDER BY A.FOOD_TYPE DESC;
