SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM AUTHOR AS A
JOIN BOOK B ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES C ON B.BOOK_ID = C.BOOK_ID
WHERE SALES_DATE LIKE '2022-01-%'
GROUP BY A.AUTHOR_ID, CATEGORY
ORDER BY A.AUTHOR_ID, CATEGORY DESC;
