SELECT B.YEAR, B.MONTH, GENDER, COUNT(*) AS USERS
FROM USER_INFO AS A
JOIN (SELECT USER_ID, YEAR(SALES_DATE) AS YEAR, 
      MONTH(SALES_DATE) AS MONTH
      FROM ONLINE_SALE
      GROUP BY USER_ID, YEAR, MONTH) B 
ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY B.YEAR, B.MONTH, GENDER
ORDER BY B.YEAR, B.MONTH, GENDER;
